// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/sysalto/report/serialization/common/report_common_proto.proto

package com.sysalto.report.serialization.common;

public final class ReportCommonProto {
  private ReportCommonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DirectDrawMovePoint_protoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.sysalto.report.serialization.common.DirectDrawMovePoint_proto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float x = 1;</code>
     */
    float getX();

    /**
     * <code>float y = 2;</code>
     */
    float getY();
  }
  /**
   * Protobuf type {@code com.sysalto.report.serialization.common.DirectDrawMovePoint_proto}
   */
  public  static final class DirectDrawMovePoint_proto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.sysalto.report.serialization.common.DirectDrawMovePoint_proto)
      DirectDrawMovePoint_protoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DirectDrawMovePoint_proto.newBuilder() to construct.
    private DirectDrawMovePoint_proto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DirectDrawMovePoint_proto() {
      x_ = 0F;
      y_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DirectDrawMovePoint_proto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {

              x_ = input.readFloat();
              break;
            }
            case 21: {

              y_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sysalto.report.serialization.common.ReportCommonProto.internal_static_com_sysalto_report_serialization_common_DirectDrawMovePoint_proto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sysalto.report.serialization.common.ReportCommonProto.internal_static_com_sysalto_report_serialization_common_DirectDrawMovePoint_proto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto.class, com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private float x_;
    /**
     * <code>float x = 1;</code>
     */
    public float getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private float y_;
    /**
     * <code>float y = 2;</code>
     */
    public float getY() {
      return y_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (x_ != 0F) {
        output.writeFloat(1, x_);
      }
      if (y_ != 0F) {
        output.writeFloat(2, y_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (x_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, x_);
      }
      if (y_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, y_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto)) {
        return super.equals(obj);
      }
      com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto other = (com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto) obj;

      boolean result = true;
      result = result && (
          java.lang.Float.floatToIntBits(getX())
          == java.lang.Float.floatToIntBits(
              other.getX()));
      result = result && (
          java.lang.Float.floatToIntBits(getY())
          == java.lang.Float.floatToIntBits(
              other.getY()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getX());
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getY());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.sysalto.report.serialization.common.DirectDrawMovePoint_proto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.sysalto.report.serialization.common.DirectDrawMovePoint_proto)
        com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_protoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sysalto.report.serialization.common.ReportCommonProto.internal_static_com_sysalto_report_serialization_common_DirectDrawMovePoint_proto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sysalto.report.serialization.common.ReportCommonProto.internal_static_com_sysalto_report_serialization_common_DirectDrawMovePoint_proto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto.class, com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto.Builder.class);
      }

      // Construct using com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        x_ = 0F;

        y_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sysalto.report.serialization.common.ReportCommonProto.internal_static_com_sysalto_report_serialization_common_DirectDrawMovePoint_proto_descriptor;
      }

      public com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto getDefaultInstanceForType() {
        return com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto.getDefaultInstance();
      }

      public com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto build() {
        com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto buildPartial() {
        com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto result = new com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto(this);
        result.x_ = x_;
        result.y_ = y_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto) {
          return mergeFrom((com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto other) {
        if (other == com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto.getDefaultInstance()) return this;
        if (other.getX() != 0F) {
          setX(other.getX());
        }
        if (other.getY() != 0F) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float x_ ;
      /**
       * <code>float x = 1;</code>
       */
      public float getX() {
        return x_;
      }
      /**
       * <code>float x = 1;</code>
       */
      public Builder setX(float value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float x = 1;</code>
       */
      public Builder clearX() {
        
        x_ = 0F;
        onChanged();
        return this;
      }

      private float y_ ;
      /**
       * <code>float y = 2;</code>
       */
      public float getY() {
        return y_;
      }
      /**
       * <code>float y = 2;</code>
       */
      public Builder setY(float value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float y = 2;</code>
       */
      public Builder clearY() {
        
        y_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.sysalto.report.serialization.common.DirectDrawMovePoint_proto)
    }

    // @@protoc_insertion_point(class_scope:com.sysalto.report.serialization.common.DirectDrawMovePoint_proto)
    private static final com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto();
    }

    public static com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DirectDrawMovePoint_proto>
        PARSER = new com.google.protobuf.AbstractParser<DirectDrawMovePoint_proto>() {
      public DirectDrawMovePoint_proto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DirectDrawMovePoint_proto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DirectDrawMovePoint_proto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DirectDrawMovePoint_proto> getParserForType() {
      return PARSER;
    }

    public com.sysalto.report.serialization.common.ReportCommonProto.DirectDrawMovePoint_proto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sysalto_report_serialization_common_DirectDrawMovePoint_proto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sysalto_report_serialization_common_DirectDrawMovePoint_proto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nAcom/sysalto/report/serialization/commo" +
      "n/report_common_proto.proto\022\'com.sysalto" +
      ".report.serialization.common\"1\n\031DirectDr" +
      "awMovePoint_proto\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002B" +
      "\002H\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_sysalto_report_serialization_common_DirectDrawMovePoint_proto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_sysalto_report_serialization_common_DirectDrawMovePoint_proto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sysalto_report_serialization_common_DirectDrawMovePoint_proto_descriptor,
        new java.lang.String[] { "X", "Y", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
